# Generated by Django 5.0.3 on 2024-07-20 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_address_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='default',
            new_name='default_billing',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='apartment_address',
            new_name='landmark',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='street_address',
            new_name='street',
        ),
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('home', 'Home'), ('office', 'Office')], default='home', max_length=10),
        ),
        migrations.AddField(
            model_name='address',
            name='default_shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
    ]
